(function(){'use strict';
const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const reduce=window.matchMedia('(prefers-reduced-motion: reduce)');
const navButton=$('.nav-toggle'),nav=$('#nav-links');
function closeNav(){nav.classList.remove('open');navButton.setAttribute('aria-expanded','false');}
navButton.addEventListener('click',()=>{const opened=nav.classList.toggle('open');navButton.setAttribute('aria-expanded',String(opened));});
nav.addEventListener('click',e=>{if(e.target.closest('a'))closeNav();});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open')){closeNav();navButton.focus();}});
document.addEventListener('click',e=>{if(!e.target.closest('.site-header'))closeNav();});
$('#year').textContent=new Date().getFullYear();
function showPrivacy(){ $('#privacy').hidden=false;$('#privacy-toggle').setAttribute('aria-expanded','true'); }
$('#privacy-toggle').addEventListener('click',()=>{const p=$('#privacy');p.hidden=!p.hidden;$('#privacy-toggle').setAttribute('aria-expanded',String(!p.hidden));});
$$('[data-open-privacy]').forEach(a=>a.addEventListener('click',showPrivacy));
if(location.hash==='#privacy')showPrivacy();
const tabs=$$('[role=tab]');
function activateTab(id,focus=false){tabs.forEach(t=>{const on=t.id===id;t.setAttribute('aria-selected',String(on));t.tabIndex=on?0:-1;$('#'+t.getAttribute('aria-controls')).hidden=!on;if(on&&focus)t.focus();});}
tabs.forEach((t,i)=>{t.addEventListener('click',()=>activateTab(t.id));t.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%tabs.length;if(e.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;if(n!==undefined){e.preventDefault();activateTab(tabs[n].id,true);}});});
const examples={website:{text:'I want a website that makes my business stand out and helps customers take the next step.',audience:'My customers',priority:'experience'},automation:{text:'I spend too much time copying customer inquiries into a spreadsheet and following up manually. I want a simpler way to keep track.',audience:'My team',priority:'time'},assistant:{text:'I want a helpful assistant that answers common customer questions and knows when to bring in a real person.',audience:'My customers',priority:'experience'},knowledge:{text:'My team’s answers are scattered across documents. I want one place to find reliable information with links to its sources.',audience:'My team',priority:'trust'},product:{text:'I have an idea for an app and want a small, usable version to see whether people find it valuable.',audience:'A new audience',priority:'validate'}};
function applyExample(key){const e=examples[key];if(!e)return;activateTab('tab-idea');$('#idea').value=e.text;$('#project-type').value=key;$('#audience').value=e.audience;$('#priority').value=e.priority;markStale();}
$$('[data-example]').forEach(b=>b.addEventListener('click',()=>{applyExample(b.dataset.example);if(b.tagName==='BUTTON')$('#idea').focus();}));
const templates={
website:{title:'A clearer digital experience',first:'One focused customer journey: understand the offer, find the right information, and take one useful next step.',deliverables:['A simple page or screen map and content outline','A responsive, working version of the core journey','Checks for usability, accessibility, and the contact or conversion path'],test:'Ask a few representative users to complete the main task without help. Observe where they hesitate.',questions:'What should a visitor do next? What content and brand assets exist? Does this need to connect to a booking, payment, or customer system?'},
automation:{title:'A workflow with less repeat work',first:'One repetitive, well-defined task, using sample data and a human approval step before any external action.',deliverables:['A before-and-after workflow and agreed exceptions','A small automation or internal tool for the main task','A visible activity log, manual fallback, and operating notes'],test:'Compare the proposed flow with the current task on a small sample. Measure net time saved, errors, and review effort.',questions:'Which tools hold the data? Are connections and permissions available? What must always be approved by a person?'},
assistant:{title:'An assistant with a useful job',first:'One audience, a small set of approved questions, and a clear route to a person when the answer is uncertain.',deliverables:['A defined role, approved source material, and boundaries','A focused text or voice experience with clear AI disclosure','Test questions, human handoff, and a proposed data-retention policy'],test:'Test common questions, missing information, misleading requests, and the handoff. Confirm the assistant does not invent answers or commitments.',questions:'What should it know? What must it never do? Is live voice necessary, and who will maintain its information and cover usage costs?'},
knowledge:{title:'Trusted answers from connected knowledge',first:'One bounded set of approved documents or data and a small number of questions people repeatedly need answered.',deliverables:['A source inventory and agreed access rules','A searchable prototype that points back to supporting sources','Checks for permissions, stale information, and unsupported answers'],test:'Compare answers with known source material. Test that users cannot access information beyond their permissions.',questions:'Where do the sources live? Who owns them? How fresh must answers be, and what data must stay out of the system?'},
product:{title:'A small product you can put in front of people',first:'One core task for one clearly defined audience. Enough to test the idea without pretending the whole product is known.',deliverables:['A simple user journey and first-version scope','A working prototype of the main interaction','A short user-test plan and decisions for the next iteration'],test:'Put the prototype in front of a few intended users. Check whether they understand it, complete the task, and want to use it again.',questions:'Who has this problem today? What do they use instead? What would make this first version worth returning to?'},
strategy:{title:'A practical starting point for AI',first:'One worthwhile use case, with a clear owner, a baseline, and explicit data and approval boundaries.',deliverables:['A small set of use cases ranked by value, effort, and risk','A hands-on pilot or team working session','Success measures, operating guardrails, and a recommended next decision'],test:'Use an agreed baseline to assess whether the pilot helps, whether people adopt it, and whether review effort outweighs the benefit.',questions:'What business problem matters most? Which AI tools are approved? Who owns the outcome and the ongoing way of working?'}
};
const priorityNotes={experience:'Watch a representative user complete the main task. Make the experience clear before adding features.',time:'Measure the current task first. Include review, exceptions, and maintenance when evaluating net time saved.',validate:'Test the riskiest assumption in the smallest useful prototype before expanding scope.',trust:'Map sensitive information, access, retention, and provider policies before connecting real data. Use approved samples first.'};
let briefExists=false;
function markStale(){if(briefExists)$('#brief-status').textContent='Inputs changed. Shape your starting point again to refresh the brief. Existing edits are kept until then.';}
['idea','project-type','audience','priority'].forEach(id=>$('#'+id).addEventListener('input',markStale));
$('#idea-form').addEventListener('submit',e=>{e.preventDefault();const idea=$('#idea').value.trim();if(!idea){$('#idea').setCustomValidity('Add a sentence about your idea.');$('#idea').reportValidity();return;}$('#idea').setCustomValidity('');const t=templates[$('#project-type').value]||templates.website;const audience=$('#audience').value;const text=['DeRomanis AI | Your starting point','','YOUR IDEA',idea,'','WHO IT IS FOR',audience,'','A POSSIBLE FIRST VERSION',t.title+'. '+t.first,'','WHAT TO MAKE',...t.deliverables.map(x=>'• '+x),'','WHAT MATTERS MOST',priorityNotes[$('#priority').value],'','HOW TO TEST IT',t.test,'','QUESTIONS TO RESOLVE',t.questions,'','BEFORE COMMITTING','Confirm feasibility, scope, data access, ownership, budget, ongoing costs, and support with Joe. These are template-based suggestions, not a quote, technical design, or confirmed commitment.','', 'Next step: joe@deromanis.com'].join('\n');$('#brief-output').value=text;$('#brief-empty').hidden=true;$('#brief-result').hidden=false;briefExists=true;$('#brief-status').textContent='Your starter brief is ready. You can edit it before copying, saving, or emailing.';$('#brief-output').focus({preventScroll:true});if(innerWidth<=600)$('#brief-result').scrollIntoView({behavior:reduce.matches?'auto':'smooth',block:'start'});});
$('#idea').addEventListener('input',()=>$('#idea').setCustomValidity(''));
$('#copy-brief').addEventListener('click',async()=>{try{if(!navigator.clipboard)throw Error('Clipboard unavailable');await navigator.clipboard.writeText($('#brief-output').value);$('#brief-status').textContent='Brief copied. Your edits are included.';}catch{const o=$('#brief-output');o.focus();o.select();$('#brief-status').textContent='Select Copy in your browser, or press Ctrl+C / Command+C. You can also use Save .txt.';}});
$('#save-brief').addEventListener('click',()=>{const b=new Blob([$('#brief-output').value],{type:'text/plain;charset=utf-8'});const u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download='DeRomanis-AI-project-brief.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(u),10000);$('#brief-status').textContent='Your edited brief has been prepared for download.';});
$('#email-brief').addEventListener('click',function(){const text=$('#brief-output').value;const budget=1500;let excerpt='';for(const ch of text){if(encodeURIComponent(excerpt+ch).length>budget)break;excerpt+=ch;}const truncated=excerpt.length<text.length;const body='Hi Joe,\n\nI would like to discuss this idea:\n\n'+excerpt+(truncated?'\n\n[Brief excerpt. I can attach the full saved brief.]':'');this.href='mailto:joe@deromanis.com?subject='+encodeURIComponent('An idea to explore | DeRomanis AI')+'&body='+encodeURIComponent(body);$('#brief-status').textContent=truncated?'Your email app will open with a short excerpt. Save and attach the full brief, or paste it into the email. Nothing was sent by this page.':'Your email app will open with the brief. Review it there before sending. Nothing was sent by this page.';});
function calculate(){const n=Number($('#tasks').value),m=Number($('#minutes').value),r=Number($('#reduction').value),h=n*m*r/6000;$('#tasks-output').value=n;$('#minutes-output').value=m+' min';$('#reduction-output').value=r+'%';$('#hours-output').value=h.toFixed(1);$('#annual-output').textContent='About '+Math.round(h*52).toLocaleString()+' hours across 52 weeks, using your assumptions.';return{n,m,r,h};}
['tasks','minutes','reduction'].forEach(id=>$('#'+id).addEventListener('input',calculate));calculate();
$('#use-calculation').addEventListener('click',()=>{const c=calculate();applyExample('automation');$('#idea').value='I repeat a task '+c.n+' times a week, taking about '+c.m+' minutes each time. I want to explore a '+c.r+'% time reduction (about '+c.h.toFixed(1)+' gross hours weekly), then check setup, review, exceptions, and costs. The task is: ';$('#idea').focus({preventScroll:true});});
// Local particle sculpture. No images, model weights, network calls, or dependencies.
const canvas=$('#universe'),ctx=canvas.getContext('2d');let paused=reduce.matches,visible=true,raf=0,angle=0,last=0,w=0,h=0;
const points=Array.from({length:260},(_,i)=>{const y=1-(i/259)*2,r=Math.sqrt(1-y*y),a=i*Math.PI*(3-Math.sqrt(5));return{x:Math.cos(a)*r,y,z:Math.sin(a)*r};});
function motionLabel(){const b=$('#motion-toggle');b.textContent=paused?'Play motion ▷':'Pause motion Ⅱ';b.setAttribute('aria-pressed',String(paused));}
function draw(time){if(!ctx)return;const dt=last?Math.min(time-last,50):0;last=time;if(!paused)angle+=dt*.000065;ctx.clearRect(0,0,w,h);const r=Math.min(w*.38,h*.38),cx=w*.5,cy=h*.48,co=Math.cos(angle),si=Math.sin(angle);const ps=points.map(p=>{const x=p.x*co-p.z*si,z=p.x*si+p.z*co;return{x:cx+(x*.94+p.y*.19)*r,y:cy+(p.y*.95-x*.13)*r,z};});for(let i=0;i<ps.length;i++){const p=ps[i];if(p.z<-.3)continue;for(let j=i+1;j<ps.length;j++){const q=ps[j];if(q.z<-.3)continue;const d=Math.hypot(p.x-q.x,p.y-q.y);if(d<r*.24&&Math.abs(p.z-q.z)<.4){ctx.strokeStyle='rgba(156,188,206,'+((1-d/(r*.24))*.16)+')';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(q.x,q.y);ctx.stroke();}}}ps.sort((a,b)=>a.z-b.z).forEach((p,i)=>{const alpha=.16+(p.z+1)*.36;ctx.beginPath();ctx.fillStyle=i%5===0?'rgba(218,255,162,'+alpha+')':'rgba(164,193,228,'+alpha+')';ctx.arc(p.x,p.y,.6+(p.z+1)*.62,0,Math.PI*2);ctx.fill();});if(!paused&&visible&&!document.hidden)raf=requestAnimationFrame(draw);else raf=0;}
function redraw(){cancelAnimationFrame(raf);last=0;draw(performance.now());}
function resize(){const box=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,1.5);w=box.width;h=box.height;canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);if(ctx)ctx.setTransform(dpr,0,0,dpr,0,0);redraw();}
$('#motion-toggle').addEventListener('click',()=>{paused=!paused;motionLabel();redraw();});motionLabel();
if(ctx){if('ResizeObserver'in window)new ResizeObserver(resize).observe(canvas);else{addEventListener('resize',resize);resize();}if('IntersectionObserver'in window)new IntersectionObserver(es=>{visible=es[0].isIntersecting;redraw();},{threshold:.05}).observe(canvas);document.addEventListener('visibilitychange',redraw);reduce.addEventListener('change',e=>{paused=e.matches;motionLabel();redraw();});}else $('#motion-toggle').hidden=true;
// Optional voice. Off by default. A public agent ID is not a secret; never add API keys here.
function setupVoice(){const config=window.DEROMANIS_CONFIG||{};const voice=config.voice||{};if(typeof voice.agentId==='string'&&/^agent_[a-zA-Z0-9_-]+$/.test(voice.agentId)){ $('#voice-box').hidden=false;$('#load-voice').addEventListener('click',()=>{const b=$('#load-voice');b.disabled=true;$('#voice-status').textContent='Loading the ElevenLabs widget. Start a conversation there only when you are ready.';const widget=document.createElement('elevenlabs-convai');widget.setAttribute('agent-id',voice.agentId);widget.setAttribute('action-text','Joe’s AI guide');widget.setAttribute('start-call-text','Talk to Joe’s AI guide');widget.setAttribute('avatar-orb-color-1','#d9ff85');widget.setAttribute('avatar-orb-color-2','#93baff');document.body.appendChild(widget);const script=document.createElement('script');script.src='https://unpkg.com/@elevenlabs/convai-widget-embed';script.async=true;let done=false;const fail=()=>{if(done)return;done=true;widget.remove();script.remove();b.disabled=false;$('#voice-status').textContent='Voice could not load. Try again, use the local studio, or email Joe.';};const timeout=setTimeout(fail,20000);script.onerror=()=>{clearTimeout(timeout);fail();};script.onload=()=>{if(done)return;done=true;clearTimeout(timeout);$('#voice-status').textContent='Widget loaded. This is AI using Joe’s voice, not Joe live. You can also contact Joe directly.';b.hidden=true;};document.body.appendChild(script);});}
const intro=config.intro||{};if(typeof intro.audioPath==='string'&&/^assets\/[a-zA-Z0-9_./-]+\.(mp3|wav|ogg)$/.test(intro.audioPath)&&!intro.audioPath.includes('..')&&intro.transcript){$('#intro-box').hidden=false;$('#intro-audio').src=intro.audioPath;$('#intro-transcript').textContent=intro.transcript;$('#intro-audio').addEventListener('error',()=>{$('#intro-box').hidden=true;});}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setupVoice);else setupVoice();
})();
